@server_HostAddress = http://localhost:5293

GET {{server_HostAddress}}/players
Accept: application/json

###
DELETE {{server_HostAddress}}/players/1

###
POST {{server_HostAddress}}/players
Content-Type: application/json

{ "id": 0, "name": "test", "rank": "grön" }

###
POST {{server_HostAddress}}/players
Content-Type: application/json

{ "id": 7, "name": "Adam", "rank": "blå" }
###
PUT {{server_HostAddress}}/players/6
Content-Type: application/json

{ "id":0, "name": "Charlie", "rank": "gul" }
###
GET {{server_HostAddress}}/teams?count=2&mode=random

###
GET {{server_HostAddress}}/teams?count=2&mode=level