@server_HostAddress = http://localhost:5293

GET {{server_HostAddress}}/weatherforecast/
Accept: application/json

###
@server_HostAddress = http://localhost:5293

GET {{server_HostAddress}}/players
Accept: application/json

###

DELETE {{server_HostAddress}}/players/

###
POST {{server_HostAddress}}/players
Content-Type: application/json

{ "id": 0, "name": "test", "rank": "grön" }

###